# Exploratory Data Analysis

In [1]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt 
import seaborn as sns

In [2]:
file_path = "C:\\Users\\ADMIN\\Desktop\\Website Traffic Analysis\\Data\\website_data.csv"

df = pd.read_csv(file_path)

In [3]:
df.head()

,Session Id,Page Views,Session Duration,Bounce Rate,Traffic Source,Time on Page,Previous Visits,Conversion Rate
0,1,5,11.051381,0.230652,Organic,3.890460,3,1.0
1,2,4,3.429316,0.391001,Social,8.478174,0,1.0
2,3,4,1.621052,0.397986,Organic,9.636170,2,1.0
3,4,5,3.629279,0.180458,Organic,2.071925,3,1.0
4,5,5,4.235843,0.291541,Paid,1.960654,5,1.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Session Id        2000 non-null   int64
 1   Page Views        2000 non-null   int64
 2   Session Duration  2000 non-null   float64
 3   Bounce Rate       2000 non-null   float64
 4   Traffic Source    2000 non-null   str
 5   Time on Page      2000 non-null   float64
 6   Previous Visits   2000 non-null   int64
 7   Conversion Rate   2000 non-null   float64
dtypes: float64(4), int64(3), str(1)
memory usage: 125.1 KB

In [5]:
df.isnull().sum()

Session Id          0
Page Views          0
Session Duration    0
Bounce Rate         0
Traffic Source      0
Time on Page        0
Previous Visits     0
Conversion Rate     0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.rename(columns={"Session Id": "session_id"}, inplace=True)
df.rename(columns={"Page Views": "page_views"}, inplace=True)
df.rename(columns={"Session Duration": "session_duration"}, inplace=True)
df.rename(columns={"Bounce Rate": "bounce_rate"}, inplace=True)
df.rename(columns={"Traffic Source": "traffic_source"}, inplace=True)
df.rename(columns={"Time on Page": "time_on_page"}, inplace=True)
df.rename(columns={"Previous Visits": "previous_visits"}, inplace=True)
df.rename(columns={"Conversion Rate": "conversion_rate"}, inplace=True)

In [8]:
df.head()

,session_id,page_views,session_duration,bounce_rate,traffic_source,time_on_page,previous_visits,conversion_rate
0,1,5,11.051381,0.230652,Organic,3.890460,3,1.0
1,2,4,3.429316,0.391001,Social,8.478174,0,1.0
2,3,4,1.621052,0.397986,Organic,9.636170,2,1.0
3,4,5,3.629279,0.180458,Organic,2.071925,3,1.0
4,5,5,4.235843,0.291541,Paid,1.960654,5,1.0

In [9]:
df["pages_per_min"] = df['page_views'] / (df['session_duration'] / 60)

In [10]:
df.head()

,session_id,page_views,session_duration,bounce_rate,traffic_source,time_on_page,previous_visits,conversion_rate,pages_per_min
0,1,5,11.051381,0.230652,Organic,3.890460,3,1.0,27.145928
1,2,4,3.429316,0.391001,Social,8.478174,0,1.0,69.984808
2,3,4,1.621052,0.397986,Organic,9.636170,2,1.0,148.052002
3,4,5,3.629279,0.180458,Organic,2.071925,3,1.0,82.661047
4,5,5,4.235843,0.291541,Paid,1.960654,5,1.0,70.824150

In [11]:
df.drop(columns=["pages_per_min"], inplace=True)

In [12]:
df.head()

,session_id,page_views,session_duration,bounce_rate,traffic_source,time_on_page,previous_visits,conversion_rate
0,1,5,11.051381,0.230652,Organic,3.890460,3,1.0
1,2,4,3.429316,0.391001,Social,8.478174,0,1.0
2,3,4,1.621052,0.397986,Organic,9.636170,2,1.0
3,4,5,3.629279,0.180458,Organic,2.071925,3,1.0
4,5,5,4.235843,0.291541,Paid,1.960654,5,1.0

In [13]:
df["user_type"] = df["previous_visits"].apply(lambda x: "New Visitor" if x == 0 else "Returning Visitor")

In [14]:
df.head()

,session_id,page_views,session_duration,bounce_rate,traffic_source,time_on_page,previous_visits,conversion_rate,user_type
0,1,5,11.051381,0.230652,Organic,3.890460,3,1.0,Returning Visitor
1,2,4,3.429316,0.391001,Social,8.478174,0,1.0,New Visitor
2,3,4,1.621052,0.397986,Organic,9.636170,2,1.0,Returning Visitor
3,4,5,3.629279,0.180458,Organic,2.071925,3,1.0,Returning Visitor
4,5,5,4.235843,0.291541,Paid,1.960654,5,1.0,Returning Visitor

In [15]:
df["conversion_status"] = np.where(df["conversion_rate"] == 1, "Converted", "Not Converted")

In [16]:
df.head()

,session_id,page_views,session_duration,bounce_rate,traffic_source,time_on_page,previous_visits,conversion_rate,user_type,conversion_status
0,1,5,11.051381,0.230652,Organic,3.890460,3,1.0,Returning Visitor,Converted
1,2,4,3.429316,0.391001,Social,8.478174,0,1.0,New Visitor,Converted
2,3,4,1.621052,0.397986,Organic,9.636170,2,1.0,Returning Visitor,Converted
3,4,5,3.629279,0.180458,Organic,2.071925,3,1.0,Returning Visitor,Converted
4,5,5,4.235843,0.291541,Paid,1.960654,5,1.0,Returning Visitor,Converted

In [17]:
df["conversion_status"].value_counts()

conversion_status
Converted        1773
Not Converted     227
Name: count, dtype: int64

In [18]:
df["time_on_page"].describe()

count    2000.000000
mean        4.027439
std         2.887422
min         0.068515
25%         1.935037
50%         3.315316
75%         5.414627
max        24.796182
Name: time_on_page, dtype: float64

In [19]:
df["bounce_rate_pct"] = df["bounce_rate"] * 100

In [20]:
df.head()

,session_id,page_views,session_duration,bounce_rate,traffic_source,time_on_page,previous_visits,conversion_rate,user_type,conversion_status,bounce_rate_pct
0,1,5,11.051381,0.230652,Organic,3.890460,3,1.0,Returning Visitor,Converted,23.065194
1,2,4,3.429316,0.391001,Social,8.478174,0,1.0,New Visitor,Converted,39.100133
2,3,4,1.621052,0.397986,Organic,9.636170,2,1.0,Returning Visitor,Converted,39.798611
3,4,5,3.629279,0.180458,Organic,2.071925,3,1.0,Returning Visitor,Converted,18.045769
4,5,5,4.235843,0.291541,Paid,1.960654,5,1.0,Returning Visitor,Converted,29.154087

In [21]:
df["traffic_source"].value_counts()

traffic_source
Organic     786
Paid        428
Referral    301
Social      269
Direct      216
Name: count, dtype: int64

In [25]:
df.groupby("traffic_source")["user_type"].value_counts()

traffic_source  user_type
Direct          Returning Visitor    179
                New Visitor           37
Organic         Returning Visitor    680
                New Visitor          106
Paid            Returning Visitor    385
                New Visitor           43
Referral        Returning Visitor    257
                New Visitor           44
Social          Returning Visitor    217
                New Visitor           52
Name: count, dtype: int64

In [27]:
df.to_csv("C:\\Users\\ADMIN\\Desktop\\Website Traffic Analysis\\Data\\website_data_cleaned.csv", index=False)